name: Terraform Lambda Image Resizer

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Terraform Stack
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write


    env:
      AWS_REGION: us-east-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies and zip lambda
      run: |
        cd lambda
        pip install -r requirements.txt -t .
        zip -r image-resizing.zip ./*
        cd ..

    - name: SetUp AWS
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.OIDC_ROLE }}
         
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
